# Generated by Django 3.2.5 on 2021-07-19 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20210719_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requestee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_requests', to='auth.user'),
        ),
    ]
