# Generated by Django 3.2.5 on 2021-08-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification',
            field=models.CharField(max_length=50),
        ),
    ]
