# Generated by Django 3.2.5 on 2021-08-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_notification_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
