# Generated by Django 3.2.5 on 2021-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('P', 'Comment'), ('R', 'Reply')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='comment',
            name='source_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_source_type',
            field=models.CharField(choices=[('R', 'Request'), ('L', 'Like'), ('CP', 'Comment'), ('CC', 'Reply'), ('M', 'Message')], max_length=2),
        ),
    ]
