# Generated by Django 3.2.5 on 2021-08-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210805_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('P', 'Comment'), ('R', 'Reply')], default='P', max_length=1),
        ),
    ]
