# Generated by Django 3.2.5 on 2021-08-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_comment_comment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_source_type',
            field=models.CharField(choices=[('R', 'Request'), ('L', 'Like'), ('P', 'Comment'), ('R', 'Reply'), ('M', 'Message')], max_length=1),
        ),
    ]
