# Generated by Django 3.2.5 on 2021-08-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_notification_notification_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('P', 'Comment'), ('C', 'Reply')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_source_type',
            field=models.CharField(choices=[('R', 'Request'), ('L', 'Like'), ('P', 'Comment'), ('C', 'Reply'), ('M', 'Message')], max_length=1),
        ),
    ]
