# Generated by Django 3.2.5 on 2021-08-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210805_0631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(null=True)),
                ('like_type', models.CharField(choices=[('P', 'Post'), ('C', 'Comment')], default='P', max_length=1)),
                ('is_like', models.BooleanField(default=False)),
            ],
        ),
    ]
