# Generated by Django 3.2.5 on 2021-08-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_source_type',
            field=models.CharField(choices=[('R', 'Request'), ('P', 'Comment'), ('C', 'Reply'), ('M', 'Message')], max_length=1),
        ),
    ]
