# Generated by Django 3.2.5 on 2021-08-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(choices=[('P', 'Comment'), ('C', 'Reply')], default='P', max_length=1),
        ),
    ]
