# Generated by Django 3.2.5 on 2021-08-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_friend_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_notification', to='core.comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_source_type',
            field=models.CharField(choices=[('R', 'Request'), ('L', 'Like'), ('C', 'Reply'), ('M', 'Message')], max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_notification', to='core.post'),
            preserve_default=False,
        ),
    ]
